### ISSUE TITLE
Document event processors in the SDK where it is supported.

### ISSUE THREAD

**Issue by rodolfoBee** [getsentry/team-sdks#102]
### Core or SDK?

Platform/SDK

### Which part? Which one?

SDKs

### Description

Multiple SDKs offer event processors that are called before the event goes into the `beforeSend` callback, but it is not described in the docs how to add them to the SDK. 

Because transaction events do not go through `beforeSend`, event processors are the only option a customer has to change data, such as scrubbing PII from transactions at the SDK level. 

In addition, we mention hints can be used in event processor and beforeSend/beforeBreadcrumb, and just mentioning it without describing 

### Suggested Solution

The event processor can be added to the filtering page as an alternative option, or have a separate session for them. A sample page can be created for the web SDKs and expanded to the other pages as the code snippets are added. 

For example, here is a code snipet for JavaScript:

```
Sentry.addGlobalEventProcessor((event, hint) => {
  // some logic
  return event
})
```

and Python:

```
from sentry_sdk.scope import add_global_event_processor

def myEventProcessor(event, hint):
    ## some logic
     return event

sentry_sdk.scope.add_global_event_processor(myEventProcessor)
```

**Comment by AbhiPrasad** [comment]
Closing this now we have `beforeSendTransaction` and `beforeSendSpan`.

In addition some SDKs do offer more granular hooks for things like replay and profiling, but we can tackle documentation for that on a more individual basis.
