### ISSUE TITLE
Project: Sentry in CI/CD

### ISSUE THREAD

**Issue by smeubank** [getsentry/team-sdks#2]
## Project Board
See our [project board](https://github.com/orgs/getsentry/projects/120/views/1) to track this initiative across all SDKs

## Description
Ideally we attempt to automate, modify, and at least provide simple methods for users to inject sentry into their CI/CD pipelines. This include providing detection, automated integration, & pragmatic documentation on why it's beneficial. The why in a nutshell is that to be able to get full advantage of Sentry, you must have Sentry as part of the full dev and software delivery life cycle. Meaning new code, new versions of app, new releases, Sentry should have all that context. So you can fix problems faster when Sentry summarizes all relevant info in front of you.

```[tasklist]
### Concrete Tasks
- [x] Remix flow in source maps
- [ ] https://github.com/getsentry/sentry-wizard/issues/418
- [ ] https://github.com/getsentry/sentry-wizard/issues/403
- [x] Webpack, Vite, TSC fallback config file create if not found
- [x] Review Docs after customer calls; Find reasons why people end up in "wrong" docs
```

Things we discussed but decided to hold off for now:
- Direct using API integrations on Vercel, Netlfy, CloudFlare etc
- Automate setting up the Sentry Vercel/netflify integration
  - env variables are set
  - build command is adjusted (if necssary)

// via Sentry client infra tooling (wizards, plugins, cli, GHAs)
 

- detect deployment platforms
  - `netlify.toml`

**Features dependent upon:**

- ~ Releases
- Upload source maps/context
- git history and suspect commits

**Hosting Provider:**
- AWS
- GCP
- Azure (azure-pipelines.yml)
- Netlify (netlify.toml)
- Vercel (???) requires special formatted env variables `PUBLIC_%`
- Cloudflare (wrangler.toml)

**CI/CD Tools:**
- GHA
- Jenkins
- Cloud Provider Pipelines

**Platform specific:**
- package.json scripts 
- webpack, vite, rollup, esbuild etc
- Nx
- Fastlane (iOS)

**Comment by Lms24** [comment]
Regarding the last task, I did some digging, reading logs from customer calls RE source maps docs and two things came up:

* Confusion around releases and our new artifact bundles when using Sentry CLI
  * Tried to clarify this in https://github.com/getsentry/sentry-docs/pull/7875
* Question around which tool to use for Vue and how docs were confusing
  * Added missing wizard snippet in https://github.com/getsentry/sentry-docs/pull/7874

I couldn't find other actionable feedback so once these PRs are merged, I'm gonna close this issue as completed. Happy to revisit docs If other things come up in the future.

**Comment by Lms24** [comment]
Closing as all concrete tasks are completed.
