### ISSUE TITLE
Remaining debugID SDK Support

### ISSUE THREAD

**Issue by ale-cota** [getsentry/team-sdks#24]
SDKs to update:
- React-Native (https://github.com/getsentry/sentry-react-native/issues/2947)
- NextJS (needs webpack plugin bump - blocked by major until v8)
- SvelteKit (needs vite plugin bump - blocked by major until v8)
- Gatsby (needs CLI bump - blocked by major until v8)
- Capacitor (???)
- Cordova (???)

**Comment by AbhiPrasad** [comment]
Considering v8 has been out for a while, I think we can close this.
