### ISSUE TITLE
XHR Fetching Experiment Follow-up

### ISSUE THREAD

**Issue by ale-cota** [getsentry/team-sdks#25]
Need to follow-up on the outcome of https://github.com/getsentry/sentry/issues/50053

**Comment by lforst** [comment]
Right now this seems successful - however, it comes with a risk that it won't easily work for our customers. I am not confident to make that call.

Unless bundlers emit a `//# debugId=` comment by themselves there is no upside to doing this. People currently still need to inject.

**Comment by stephanie-anderson** [comment]
We should keep this on Project Artifact Bundles, but remove it from the projects overview project (since this is not a project) 😬

**Comment by AbhiPrasad** [comment]
@lforst @stephanie-anderson can we close this issue?

**Comment by lforst** [comment]
yeah
