### ISSUE TITLE
Materialize Envelopes Always

### ISSUE THREAD

**Issue by dcramer** [getsentry/team-sdks#34]
### Description

Currently SDKs short-circuit event/envelope creation in a variety of circumstances, and in non-uniform ways.

For example, when the DSN isnt set, the JavaScript SDK will short-circuit sending:

- After some envelopes are created
- Before some event begin
- Without triggering any integration code

These all create different runtime profiles, which in itself is a problem (if you believe in the mantra of having dev as close to prod as feasible), but its also not well documented for how this should work.

To enable [Spotlight](https://github.com/getsentry/spotlight/issues/1) we need full materialization of envelopes even with then DSN isnt set. What this means is TBD - for example should profiling always run even when the DSN is disabled?) - but its clear that it at the very least means this behavior needs well defined to be implemented across various SDKs.

**Comment by dcramer** [comment]
Relevant example of changes required in JavaScript, excluding the transport and worker code (which are Spotlight specific): https://github.com/getsentry/sentry-javascript/compare/feat/hackweek-2023-spotlight

**Comment by dcramer** [comment]
Quick note: while this shouldnt matter in dev, we should figure out a path where we know if the SDK is in dev/prod. If you dont set SENTRY_DSN in prod we do not want to increase load.

**Comment by HazAT** [comment]
I think we can close this, Spotlight works everywhere
