### ISSUE TITLE
Project: Sentry Developer Metrics (SDM/DDM)

### ISSUE THREAD

**Issue by stephanie-anderson** [getsentry/team-sdks#36]
### Description

Metrics! Sentry will support Metrics finally! First we need all of our SDKs to support Metrics, this ticket is track the implementation and rollout of Metrics across sentry SDKs. Specification for implementation is in the develop spec linked below.

[Project Board](https://github.com/orgs/getsentry/projects/198/views/1)

**Related to requirement of adding Metrics to each SDK**:
- [ ] Metrics API
- [ ] Metrics summaries 
- [ ] Span Aggregator (trace correlation)
- [ ] code location
- [ ] Normalizaiton https://github.com/getsentry/team-sdks/issues/56
- [ ] SDK Docs

**Related to product and onboarding:**

> Regarding metrics onboarding, we want to follow the Install , Configure , Verify  structure.
> The steps that need to be done are:
> Add the platforms to the list of platforms that support custom metrics (customMetricBackendPlatforms & customMetricFrontendPlatforms ) in [platformCategories.tsx](https://github.com/getsentry/sentry/blob/640cfea5db20402b7154ccd9c041f4701f5f34ca/static/app/data/platformCategories.tsx#L382)
> Add the onboarding content as customMetricsOnboarding entry to the Docs object exported by the platform'd docs file (e.g. [rust](https://github.com/getsentry/sentry/blob/640cfea5db20402b7154ccd9c041f4701f5f34ca/static/app/gettingStartedDocs/rust/rust.tsx#L163))
> You can find an example PR that does this for serverless javascript platforms [here](https://github.com/getsentry/sentry/pull/64540/files).
> ATM the guides are very uniform in their content. We collected them [here](https://www.notion.so/sentry/Onboarding-guides-0e1853c2730d422f81c689b9a1daac45) in Notion

- [ ] Project Creation Onboarding [Getting Started Doc](https://develop.sentry.dev/frontend/working-on-getting-started-docs/)
- [ ] Set Up Custom Metrics Wizard [here](https://github.com/getsentry/sentry/blob/master/static/app/components/onboarding/gettingStartedDoc/utils/metricsOnboarding.tsx) & .NET example [here](https://github.com/getsentry/sentry/tree/master/static/app/gettingStartedDocs/dotnet)
- [ ] Tested with sample app - Docs and Product Onboarding

The list of available features per SDK to update with new developments: https://docs.google.com/spreadsheets/d/14cjYBAWI6RkDilqXYAsLYa89wIWdQJq350fjwqT1uyI/edit#gid=0

### Slack-Channel

#discuss-ddm

### Document(s)

- [Develop Specs](https://develop.sentry.dev/delightful-developer-metrics/)

### Stakeholder(s)

- Armin
- Indragie

### Team(s)

Mobile, Web Backend, Web Frontend

```[tasklist]
### SDKs
- [x] JS Browser:  > https://github.com/getsentry/sentry-javascript/releases/tag/7.88.0
- [x] JS Server (node et al): > https://github.com/getsentry/sentry-javascript/releases/tag/7.91.0
- [ ] JS Browser code locations
- [ ] JS Node code locations
- [x] Python
- [ ] https://github.com/getsentry/sentry-php/releases/tag/4.3.0
- [ ] https://github.com/getsentry/sentry-ruby/issues/2246
- [ ] https://github.com/getsentry/sentry-java/issues/3190
- [ ] https://github.com/getsentry/sentry-go/issues/787
- [ ] https://github.com/getsentry/sentry-elixir/issues/692
- [ ] Rust: `experimental` https://github.com/getsentry/sentry-rust/releases/tag/0.32.1
- [x] .NET: https://github.com/getsentry/sentry-dotnet/releases/tag/4.0.0
- [ ] https://github.com/getsentry/sentry-cocoa/issues/3631
- [x] Android: > https://github.com/getsentry/sentry-java/issues/3190 (currently tracking together with Java)
- [ ] https://github.com/getsentry/sentry-dart/issues/1876
- [ ] https://github.com/getsentry/sentry-react-native/issues/3578
- [ ] https://github.com/getsentry/sentry-native/issues/953
- [ ] https://github.com/getsentry/sentry-docs/issues/9178
- [ ] https://github.com/getsentry/sentry-unreal/issues/497
- [ ] https://github.com/getsentry/sentry/pull/66960
```

**Comment by ale-cota** [comment]
@kahest could you please add/link also the mobile work issues, so we can have them tracked all in one place? 🙏 thank you!

**Comment by kahest** [comment]
@ale-cota done - for Android we currently track together with [Java](https://github.com/getsentry/sentry-java/issues/3190), we'll split if necessary. also it's unclear whether/when we'll add for `sentry-native`
