### ISSUE TITLE
[crons] Enable client reports

### ISSUE THREAD

**Issue by gaprl** [getsentry/team-sdks#42]
### Description

We've recently added support for client reports for Crons using the `monitor` data category. Adding support to all of our SDKs would be helpful to troubleshoot customers if their check-ins are getting discarded for some reason (network issues, rate limits, etc).

### Slack-Channel

#discuss-crons

**Comment by antonpirker** [comment]
Just to double check @gaprl: The envelope item type for monitor check-ins is `check_in` and the data category for client reports should be `monitor`. Is this correct?

**Comment by gaprl** [comment]
> Just to double check @gaprl: The envelope item type for monitor check-ins is `check_in` and the data category for client reports should be `monitor`. Is this correct?

Correct

**Comment by stephanie-anderson** [comment]
Will close in favour of this one: https://github.com/getsentry/team-sdks/issues/11
