### ISSUE TITLE
[crons] check-in attachments support

### ISSUE THREAD

**Issue by gaprl** [getsentry/team-sdks#45]
### Description

In Q1, we are planning on implementing the ability to attach files to a check-in and potentially context as well.

On attachments, it's likely we'll update the [attachment envelope](https://develop.sentry.dev/sdk/envelopes/#attachment) to support a check-in ID or a new envelope dedicated for check-in attachments. We'll discuss with ingest and update with requirements here.

The idea is to enable customers to attach log files and other relevant metadata for each job run.

### Team(s)

Web backend: all Crons SDKs

**Comment by stephanie-anderson** [comment]
Closing in favour of https://github.com/getsentry/team-sdks/issues/11
