### ISSUE TITLE
[Chore] Implement Tag Normalization/Restrictions 

### ISSUE THREAD

**Issue by smeubank** [getsentry/team-sdks#56]
### Description

Related to the [project](https://github.com/getsentry/team-sdks/issues/36) for implement Metrics in all SDKs, and using the same [project board](https://github.com/orgs/getsentry/projects/198/views/1).

All SDKs and ingestion needs to consider data normalization for Metrics (tags) as we do today for transactions. The simple requirement:
- **Whatever logic the SDKs and relay use today for normalizing should apply to Metrics data as well**

Parent Sentry issue: https://github.com/getsentry/sentry/issues/64541

For SDKs where Metrics has already been added, this needs to be checked and added where required. For SDKs where this has not been added it will be a requirements of the initial implementation.

### Document(s)

- [Develop Specs](https://develop.sentry.dev/delightful-developer-metrics/)
- [Metrics Normalization](https://develop.sentry.dev/sdk/metrics/#normalization)
- [Dev Spec PII and Data Scrubbing](https://develop.sentry.dev/pii/)

```[tasklist]
### SDKs
- [ ] Dev Spec Update
- [x] Check: JS Browser
- [x] Check: JS Server (node et al)
- [ ] Check: Python
- [ ] Check: PHP
- [ ] Check: Rust
- [ ] Check: .NET
- [ ] https://github.com/getsentry/sentry-java/issues/3190
- [ ] https://github.com/getsentry/sentry-react-native/issues/3578
- [ ] Golang
- [ ] Ruby
- [ ] Elixir
- [ ] iOS
- [x] Android
- [ ] Game engines
- [ ] Native
```

### Slack-Channel

#discuss-ddm

### Stakeholder(s)

- Armin
- Matej & Ale

### Team(s)

Mobile, Web Backend, Web Frontend, Ingest

**Comment by stephanie-anderson** [comment]
Guess this will be obsolete now, @smeubank

**Comment by stephanie-anderson** [comment]
Closing as Metrics was shut down in its current form
