### ISSUE TITLE
Validate that all SDK tooling works with hybrid cloud (region routing)

### ISSUE THREAD

**Issue by AbhiPrasad** [getsentry/team-sdks#68]
### Description

https://getsentry.atlassian.net/browse/INC-667

https://www.notion.so/sentry/INC-667-Sourcemap-uploading-does-not-work-b3b5ad07a7e240d185de03a5a0b4f48b

To ensure that we don't run into more incidents like we did with INC-667, we should validate that all SDK related tooling works with hybrid cloud.

Related: https://www.notion.so/sentry/Region-Safe-Uploads-Spec-b431fa85b77e48808ff6eeaf6c61163e

**Comment by AbhiPrasad** [comment]
Github action relies on `sentry-cli` https://github.com/getsentry/action-release

**Comment by stephanie-anderson** [comment]
@AbhiPrasad @mydea I think we can close this issue?

**Comment by AbhiPrasad** [comment]
Yes we can close it, we've not gotten any reports about the EU region in the last 1 month as well.
