### ISSUE TITLE
Transparent Feature Onboarding

### ISSUE THREAD

**Issue by HazAT** [getsentry/team-sdks#81]
### Description

Today, in the Sentry onboarding, we are very transparent about what features will be enabled in the SDKs 
It's on the top and the code snippet dynamically changes

<img width="1401" alt="image" src="https://github.com/getsentry/team-sdks/assets/363802/011a0141-0059-4325-97f3-5b9201a5b693">

We want to have the same experience in our platform docs on https://docs.sentry.io/

as well as in our Wizard.

It can still be default to YES (so it can be opt-out) tho it has to be a question we should ask or in your face to decide.

### Why should we be doing this?

With the upcoming plan AM3 (Pay as you Go) you pay what you consume. 
There is a churn risk involved (already today) if you send stuff that you don't need or, even worse, don't want and even pay for - We need to be super transparent so no one can say we didn't clearly state it.

### Why now?

AM3 is planned to ship May 15th, so we should be prepared.

### Stakeholder(s)

Daniel

### Team(s)

Mobile, Backend, Frontend

**Comment by stephanie-anderson** [comment]
This has been shipped on June 11th. We will further improve the pages by including all possible products as options, and also make sure that the `Verfiy` step actually contains ways to verify if each of those features were successfully configured
